# gsv2p_tts_plugin - 自动生成的配置文件
# 基于 artrajz-vits-simple-api 的文本转语音插件，支持多种语言和音色。

# 插件基本配置
[plugin]

# 是否启用插件
enabled = true


# 组件启用控制
[components]

# 是否启用Action组件
action_enabled = true

# 是否启用Command组件
command_enabled = true


# GSV2P API配置
[gsv2p]

# GSV2P API地址
api_url = "https://gsv2p.acgnai.top/v1/audio/speech"

# API认证Token
api_token = "your_api_token_here"

# 默认音色
default_voice = "原神-中文-派蒙_ZH"

# API请求超时时间（秒）
timeout = 60

# TTS模型
model = "tts-v4"

# 音频格式
response_format = "mp3"

# 语音速度
speed = 1.0

# 文本语言
text_lang = "中英混合"

# 提示语言
prompt_lang = "中文"

# 情感
emotion = "默认"

# Top-K采样
top_k = 10

# Top-P采样
top_p = 1.0

# 温度参数
temperature = 1.0

# 文本分割方法
text_split_method = "凑四句一切"

# 批处理大小
batch_size = 1

# 批处理阈值
batch_threshold = 0.75

# 是否分桶
split_bucket = true

# 片段间隔
fragment_interval = 0.3

# 是否并行推理
parallel_infer = true

# 重复惩罚
repetition_penalty = 1.35

# 采样步数
sample_steps = 16

# 是否超分辨率
if_sr = false

# 随机种子
seed = -1


